const express = require("express")
const auth = require("../middleware/auth");
const router = express.Router()
const {onBoarding, login, userConnection, logout, reccomendingCalorie, forgotPasswordCode, checkDigits, resetPassword} = require('../Functions/onBoarding')
const {mealList,mealListSearch} = require('../Functions/meals')
const {recipes, recipeSearch, selectRecipe} = require('../Functions/recipes')
const{generatePlan} = require('../Functions/Schedule');
const {totalCalorie} = require('../Functions/totalCalorie')
const {changingDailyCalorieNeed, editProfile} = require('../Functions/editProfile')
const {createCustomPlate, selectIngredient, saveCustomPlate, platesList} = require('../Functions/customPlate')
const verifyToken = require("../middleware/auth");

router.route("/signup").post(onBoarding)
router.route("/forgotPasswordCode").post(forgotPasswordCode)
router.route("/checkDigits").post(checkDigits)
router.route("/reccomendingCalorie").post(reccomendingCalorie)
router.route("/resetPassword").post(resetPassword)
router.route('/login').post(login)
// router.route('/userConnection').post(verifyToken,userConnection)
router.route('/logout').post(verifyToken,logout)
router.route('/mealList',).post( mealList)
router.route('/mealListSearch').post(mealListSearch)
router.route('/recipes').post(recipes)
router.route('/recipeSearch').post(verifyToken,recipeSearch)
router.route('/selectRecipe').post(selectRecipe)
router.route('/generatePlan').post(verifyToken,generatePlan)
router.route('/dailyCalorie').get(verifyToken, totalCalorie)
router.route('/changingDailyCalorieNeed').post(verifyToken, changingDailyCalorieNeed)
router.route('/editProfile').post(verifyToken, editProfile)
router.route('/createCustomPlate').post(verifyToken, createCustomPlate)
router.route('/selectIngredient').post(verifyToken, selectIngredient)
router.route('/saveCustomPlate').post(verifyToken, saveCustomPlate)
router.route('/platesList').get(verifyToken, platesList)
module.exports = router