const express = require("express")
const auth = require("../middleware/auth");
const router = express.Router()
const {onBoarding, login, userConnection, logout, reccomendingCalorie, forgotPasswordCode, checkDigits, resetPassword} = require('../Functions/onBoarding')
const {mealList, mealSearch, mealSelect} = require('../Functions/meals')
const {recipes, recipeSearch, selectRecipe} = require('../Functions/recipes')
const{generatePlan} = require('../Functions/Schedule');
const {totalCalorie} = require('../Functions/totalCalorie')
const {changingDailyCalorieNeed, editProfile} = require('../Functions/editProfile')
const {createCustomPlate, selectIngredient, saveCustomPlate, platesList} = require('../Functions/customPlate')
const verifyToken = require("../middleware/auth");

router.route("/foodtracker/signup").post(onBoarding)
router.route("/foodtracker/forgotPasswordCode").post(forgotPasswordCode)
router.route("/foodtracker/checkDigits").post(checkDigits)
router.route("/foodtracker/reccomendingCalorie").post(reccomendingCalorie)
router.route("/foodtracker/resetPassword").post(resetPassword)
router.route('/foodtracker/login').post(login)
// router.route('/userConnection').post(verifyToken,userConnection)
router.route('/foodtracker/logout').post(verifyToken,logout)
router.route('/foodtracker/mealList').get(verifyToken, mealList)
router.route('/foodtracker/mealSearch').get(verifyToken, mealSearch)
router.route('/foodTracker/mealSelect').post(verifyToken,mealSelect)
router.route('/foodtracker/recipes').get(verifyToken,recipes)
router.route('/foodtracker/recipeSearch').post(verifyToken,recipeSearch)
router.route('/foodtracker/selectRecipe').post(verifyToken,selectRecipe)
router.route('/foodtracker/generatePlan').post(verifyToken,generatePlan)
router.route('/foodtracker/dailyCalorie').get(verifyToken, totalCalorie)
router.route('/foodtracker/changingDailyCalorieNeed').post(verifyToken, changingDailyCalorieNeed)
router.route('/foodtracker/editProfile').post(verifyToken, editProfile)
router.route('/foodtracker/createCustomPlate').post(verifyToken, createCustomPlate)
router.route('/foodtracker/selectIngredient').post(verifyToken, selectIngredient)
router.route('/foodtracker/saveCustomPlate').post(verifyToken, saveCustomPlate)
router.route('/foodtracker/platesList').get(verifyToken, platesList)
module.exports = router